version: '3.5'

services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: iogt
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: iogt.settings.docker_compose_dev
      COMMIT_HASH: asdfghjkl
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - db
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.12.1'
    environment:
      - discovery.type=single-node
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: iogt
    volumes:
      - /var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

volumes:
  es-data01:
